name: advstory
description: An advanced, complete story viewer. Has support for images, videos, custom widget contents, gestures, interceptors, listeners, manipulators and much more.
version: 0.2.0
homepage: https://advstory.sourcekod.com
repository: https://github.com/ertgrulll/advstory
issue_tracker: https://github.com/ertgrulll/advstory/issues
maintainer: ErtuÄŸrul YakÄ±n (@ertgrulll)

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  shimmer: ^2.0.0
  video_player: ^2.4.5

dev_dependencies:
  dartdoc: ^6.0.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: